version: '3'

env:
  MAIN_FILE: cmd/main/main.go
  UTIL_SCRIPT_FILE: scripts/util/main/main.go
  MOCKGEN_TEST_SCRIPT_FILE: scripts/mockgen_test/main/main.go
  DEV_CFG_FILE: config/dev.yaml

tasks:
  build:
    cmds:
      - go build $MAIN_FILE
  script:
    cmds:
      - go build $UTIL_SCRIPT_FILE
      - ./main
      - rm main
  dev:
    cmds:
      - CONFIG_PATH=$DEV_CFG_FILE go run $MAIN_FILE
  client:
    cmds:
      - go run client/main.go
  mockgen-test:
    cmds:
      - go build $MOCKGEN_TEST_SCRIPT_FILE
      - ./main
      - rm main
  migration-setup:
    cmds:
      - export GOOSE_DRIVER=postgres
      - export GOOSE_DBSTRING=postgresql://eer0:hahaha4142@localhost:5500/mirage-auth-service?sslmode=disable