env: "prod"
api_key: "your_super_puper_auth_service_key"
access_token_time: "48h"
refresh_token_time: "128h"
admin_name: "eer0"
admin_password: "Illidan4142"
http_server:
  address: "${SERVER_PORT}"
  timeout: 4s
  idle_timeout: 30s
postgres:
  host: "${POSTGRES_HOST}"
  port: ${POSTGRES_PORT}
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  dbname: "${POSTGRES_DBNAME}"